[default]
vers = 'v1.2.3'

[prod]
in_path = 'IN'
out_path = 'OUT'
db_path = 'db/tmp-c.db'

[dev]
in_path = './IN'
out_path = './OUT'
db_path = 'db/tmp.db'

[test]
in_path = '../IN'
out_path = '../OUT'
db_path = '../db/tmp-test.db'
test_in_path = 'Test_IN'

